[project]
name = "data-extractor"
version = "0.1.0"
description = "GenAI data extraction project"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["."]